### ISSUE TITLE
setAsFrameless compatibility

### ISSUE THREAD

**Issue by DJafari** [leanflutter/window_manager#14]
in readme not specified `setAsFrameless` method
can i know which platform supported it ?

another question, for example `setClosable` not available in windows, if i call it in windows, you handle exception or i must do it ?

**Comment by lijy91** [comment]
The setAsFrameless method currently supports three platforms, but hiddenWindowAtLaunch has not yet been implemented in windows and linux, you will still see that it is due to the normal window to the frameless window.

For methods that are not supported, you need to determine the platform before calling.

**Comment by lijy91** [comment]
`v0.1.1` has been released and already contains the `setClosable` method
