### ISSUE TITLE
How to hide window on startup?

### ISSUE THREAD

**Issue by prateekmedia** [leanflutter/window_manager#206]
Is there any way to hide window on startup for linux?

**Comment by FeodorFitsner** [comment]
Maybe I've found the solution.

Open `linux\my_application.cc` for editing and find the following lines:

```cc
  gtk_window_set_default_size(window, 1280, 720);
  gtk_widget_show(GTK_WIDGET(window));
```

add `gtk_widget_hide(GTK_WIDGET(window));` below that block:

```cc
  gtk_window_set_default_size(window, 1280, 720);
  gtk_widget_show(GTK_WIDGET(window));
  gtk_widget_hide(GTK_WIDGET(window));
```

I'm testing on WSL and it kind of works. :)

**Comment by prateekmedia** [comment]
@FeodorFitsner I tried it but it messes up the size of the window :(

**Comment by FeodorFitsner** [comment]
Alright, let's wait for an official solution then? 🤷🏻‍♂️

**Comment by alexmercerind** [comment]
I'm having similar problem. That period of "2 seconds with no paint" at start-up is driving me crazy.

The `FlView` from Flutter seems to be very tightly coupled with GTK.
GTK does not render frames when it is hidden.

In essence, what an approach should be that window launches without any visibility at startup & then Dart-VM/Flutter notifies back to GTK through platform channels that "first frame has been rasterized, now we're ready to actually show the window.".
[waitUntilFirstFrameRasterized](https://api.flutter.dev/flutter/widgets/WidgetsBinding/waitUntilFirstFrameRasterized.html) can be used for this.

But since, when window is hidden (using `gtk_widget_hide` or `gtk_widget_set_visible`), no frames ever get drawn & [waitUntilFirstFrameRasterized](https://api.flutter.dev/flutter/widgets/WidgetsBinding/waitUntilFirstFrameRasterized.html) itself never gets invoked.

So, an another approach to make window invisible is using:

- `gtk_widget_set_opacity` (make it invisible using opacity as `0.0`)
- `gtk_widget_set_sensitive` (make it un-clickable with `false`)

By this, [waitUntilFirstFrameRasterized](https://api.flutter.dev/flutter/widgets/WidgetsBinding/waitUntilFirstFrameRasterized.html) actually gets called & Flutter gets rendered. Once, [waitUntilFirstFrameRasterized](https://api.flutter.dev/flutter/widgets/WidgetsBinding/waitUntilFirstFrameRasterized.html) is received notify back GTK with:

- `gtk_widget_hide` (on `window` object)
- `gtk_widget_set_opacity` (make it invisible using opacity as `1.0`)
- `gtk_widget_set_sensitive` (make it un-clickable with `true`)
- `gtk_widget_show` (on `window` object)

Having `gtk_widget_hide` & `gtk_widget_show` makes window to show actual "open animation" (as configured by the window manager or desktop-environment) because just changing opacity will just make window appear instantly.


The problem still with this is that, we'll still have a window (though invisible, non-clickable & completely undetectable) during that "2 seconds with no paint", which can result in some weird situations for some things like tiling window managers, I guess.

This is the only solution, otherwise I just feel Flutter will need changes in [flutter/engine](https://github.com/flutter/engine) itself.

**Comment by Merrit** [comment]
Have you tried `gtk_widget_realize`?

```dart
  /// Hide window by default so we can manipulate size, frame, etc and 
  /// then show the window when we are ready.
  ///
  /// `gtk_widget_realize` will create the window without showing it, 
  /// then the Dart code can call `windowManager.show();`.
  // gtk_widget_show(GTK_WIDGET(window));   <-- Previous implementation.
  gtk_widget_realize(GTK_WIDGET(window));
  ```

**Comment by lijy91** [comment]
@Merrit Thanks a lot for the info, I'll add it to the readme

**Comment by tgrushka** [comment]
Latest Flutter 3.24 breaks the `gtk_widget_realize` solution.

Now, to hide on startup in Linux:

Leave as-is:
```
  gtk_window_set_default_size(window, 1280, 720);
  gtk_widget_show(GTK_WIDGET(window));
```

Hide window below `fl_register_plugins`:
```
  fl_register_plugins(FL_PLUGIN_REGISTRY(view));
  gtk_widget_hide(GTK_WIDGET(window));
```

See @Merrit 's comment:
https://github.com/leanflutter/window_manager/issues/179#issuecomment-2299534856
